

CCC_ANALYZER_DIR    =   /usr/share/clang/scan-build-11/libexec



# CMAKE_CFLAGS_OPTIONS   +=
# CMAKE_CXXFLAGS_OPTIONS +=
# CMAKE_LDFLAGS_OPTIONS  +=

CMAKE_TARGET_OPTIONS   += -DCMAKE_C_COMPILER="$(CCC_ANALYZER_DIR)/ccc-analyzer"
CMAKE_TARGET_OPTIONS   += -DCMAKE_CXX_COMPILER="$(CCC_ANALYZER_DIR)/ccc-analyzer"

