
COVERAGE_OPTIONS        = --coverage


CMAKE_CFLAGS_OPTIONS   += $(COVERAGE_OPTIONS)
CMAKE_CXXFLAGS_OPTIONS += $(COVERAGE_OPTIONS)
CMAKE_LDFLAGS_OPTIONS  += $(COVERAGE_OPTIONS)
# CMAKE_TARGET_OPTIONS +=

